#used to execute all makefile instructions
all: divide.exe string.exe sum1.exe sum2.exe string2.exe

#cleans out the bin folder containing the executables
clean:
	rm ../../bin/*.exe

#instructions for creating divide executable file
divide.exe: divide.cpp
	g++ -o ../../bin/divide.exe divide.cpp

#instructions for creating string executable file
string.exe: string.cpp
	g++ -o ../../bin/string.exe string.cpp

#instructions for creating sum1 executable file
sum1.exe: sum1.cpp
	g++ -o ../../bin/sum1.exe sum1.cpp

#instructions for creating sum2 executable file
sum2.exe: sum2.cpp
	g++ -o ../../bin/sum2.exe sum2.cpp

#instructions for creating string2 executable file
string2.exe: string2.cpp
	g++ -o ../../bin/string2.exe string2.cpp
