#instruction for creating every executable file
all: type-safe.exe const_mod.exe two_ints.exe two_floats.exe seq_ints.exe seq_string.exe tiny_calc.exe ctof_v1.exe ctof_v2.exe

#cleans out the bin folder containing the executables
clean:
	rm ../../bin/*.exe

#instructions for creating type-safe.exe executable file
type-safe.exe: type-safe.cpp
	g++ -o ../../bin/type-safe.exe type-safe.cpp
#instruction to execute the type-safe.exe file
run01: 
	@echo ---------------------
	@echo Running type-safe.exe
	../../bin/type-safe.exe
	@echo

#instructions for creating const_mod.exe executable file
const_mod.exe: const_mod.cpp
	g++ -o ../../bin/const_mod.exe const_mod.cpp
#instruction to execute the const_mod.exe file
run02: 
	@echo ---------------------
	@echo Running const_mod.exe
	../../bin/const_mod.exe
	@echo

#instructions for creating two_ints.exe executable file
two_ints.exe: two_ints.cpp
	g++ -o ../../bin/two_ints.exe two_ints.cpp
#instruction to execute the two_ints.exe file
run03: 
	@echo ---------------------
	@echo Running two_ints.exe
	../../bin/two_ints.exe
	@echo

#instructions for creating two_floats.exe executable file
two_floats.exe: two_floats.cpp
	g++ -o ../../bin/two_floats.exe two_floats.cpp
#instruction to execute the two_floats.exe file
run04: 
	@echo ---------------------
	@echo Running two_floats.exe
	../../bin/two_floats.exe
	@echo

#instructions for creating seq_ints.exe executable file
seq_ints.exe: seq_ints.cpp
	g++ -o ../../bin/seq_ints.exe seq_ints.cpp
#instruction to execute the seq_ints.exe file
run05: 
	@echo ---------------------
	@echo Running seq_ints.exe
	../../bin/seq_ints.exe
	@echo

#instructions for creating seq_string.exe executable file
seq_string.exe: seq_string.cpp
	g++ -o ../../bin/seq_string.exe seq_string.cpp
#instruction to execute the seq_string.exe file
run06: 
	@echo ---------------------
	@echo Running seq_string.exe
	../../bin/seq_string.exe
	@echo

#instructions for creating tiny_calc.exe executable file
tiny_calc.exe: tiny_calc.cpp
	g++ -o ../../bin/tiny_calc.exe tiny_calc.cpp
#instruction to execute the tiny_calc.exe file
run07: 
	@echo ---------------------
	@echo Running tiny_calc.exe
	../../bin/tiny_calc.exe
	@echo

#instructions for creating ctof_v1.exe executable file
ctof_v1.exe: ctof_v1.cpp
	g++ -o ../../bin/ctof_v1.exe ctof_v1.cpp
#instruction to execute the ctof_v1.exe file
run08: 
	@echo ---------------------
	@echo Running ctof_v1.exe
	../../bin/ctof_v1.exe
	@echo

#instructions for creating ctof_v2.exe executable file
ctof_v2.exe: ctof_v2.cpp
	g++ -o ../../bin/ctof_v2.exe ctof_v2.cpp
#instruction to execute the ctof_v2.exe file
run09: 
	@echo ---------------------
	@echo Running ctof_v2.exe
	../../bin/ctof_v2.exe
	@echo